In [12]:
import pandas as pd
import requests

In [17]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=61edce02e942091acaf4ea3adf20e348&language=en-US&page=1')

In [14]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [15]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.322,659
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.890,2052
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30931
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.700,3855

In [19]:
df=pd.DataFrame()

In [25]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,231.0192,9.322,659
1,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,24.2800,8.941,339
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,64.2663,8.890,2052
3,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,75.4156,8.727,30931
4,936075,Michael,"The story of Michael Jackson, one of the most ...",2026-04-22,102.8294,8.700,3855
...,...,...,...,...,...,...,...
19995,19912,The Final Destination,A horrifying premonition saves a young man and...,2009-08-26,9.7937,5.614,3973
19996,18998,Darkman II: The Return of Durant,Darkman and Durant return and they hate each o...,1995-07-11,2.7332,5.600,304
19997,10329,Congo,Eight people embark on an expedition into the ...,1995-06-09,5.2967,5.614,1005
19998,523931,Megalodon,A military vessel on the search for an unident...,2018-08-10,3.2744,5.613,322
19999,185341,[REC]⁴ Apocalypse,"Ángela Vidal, the young television reporter wh...",2014-10-31,4.1348,5.613,1287

In [29]:
for i in range(1,420):
  response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=61edce02e942091acaf4ea3adf20e348&language=en-US&page={}'.format(i))
  temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df = pd.concat([df, temp_df], ignore_index=True)

In [30]:
df.shape

(28380, 7)

In [31]:
df.to_csv('movies.csv')